---
- name: IOS-XR Cores Configuration Tasks

  block:
    - name: Include vars for this role (xr_prefix_lists)
      include_vars:
        file: vars.yml
        name: xr_prefix_lists

    - name: Configure Prefix-Set VRF-CE1A-OSPF2BGP
      cisco.iosxr.iosxr_config:
        lines:
          - "{{ item }}"
        parents: prefix-set VRF-CE1A-OSPF2BGP
      loop: "{{ xr_prefix_lists.prefix_sets.VRF_CE1A_OSPF2BGP }}"
    
    - name: Configure Prefix-Set VRF-CE2A-OSPF2BGP
      cisco.iosxr.iosxr_config:
        lines:
          - "{{ item }}"
        parents: prefix-set VRF-CE2A-OSPF2BGP
      loop: "{{ xr_prefix_lists.prefix_sets.VRF_CE2A_OSPF2BGP }}"