---
- name: IOS-XR Cores Configuration Tasks

  block:

    - name: Configure Prefix-Set VRF-CE1A-OSPF2BGP
      cisco.iosxr.iosxr_config:
        src: "vars/CE1A.j2"
    
    - name: Configure Prefix-Set VRF-CE2A-OSPF2BGP
      cisco.iosxr.iosxr_config:
        src: "vars/CE2A.j2"